### ISSUE TITLE
Gateway - Hummingbot client crashed after gateway relaunch on a change of config

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/gateway#414]
### Describe the bug

When testing https://github.com/hummingbot/gateway/pull/403 and accidentally added a wrong nodeURL using `gateway config` command, observed that after it reconnected and successfully updated the config and you happen to closed the gateway connection manually the connection to port `15888` is still active 

![Image](https://github.com/user-attachments/assets/7233cedf-ee8a-4cdb-9c36-cf418f09dfd3)
- On the screenshot above, the gateway was already closed and run `lsof -t :15888` to list where 15888 is active

![Image](https://github.com/user-attachments/assets/f34c22bb-16c9-4c68-8c88-10dc38bb7cac)
- On the screenshot, observed that hummingbot crashed `539628 killed bin/hummingbot_quickstart.py -p a`

### Steps to reproduce

1. Update any config using `gateway config` and wait until it reconnects
2. On terminal, manually close gateway and run `lsof -t :15888` to check if port 15888 still in use
3. Relaunch gateway and observe hummingbot client

### Release version

dev-2.4.0

### Type of installation

Source

### Attach required files

na

**Comment by fengtality** [comment]
I believe this bug is now fixed in v2.8, but please confirm.

**Comment by rapcmia** [comment]
> I believe this bug is now fixed in v2.8, but please confirm.

This is still existing issue:
<img width="2048" height="1220" alt="Image" src="https://github.com/user-attachments/assets/a4cf126e-f365-4205-bce6-24a6d6b727ae" />
-  To reproduce:
    - On hummingbot, update any gateway config and wait until gateway reconnects successfully
    - On gateway, relaunch gateway
